import Link from "next/link"
import { ArrowRight, Check, ChevronRight, Clock3, Droplets, Hammer, Home, MapPin, MessageCircle, Phone, Ruler, ShieldCheck, Sparkles, Star, Wrench } from "lucide-react"

const services = [
  ["Gypsum False Ceiling", "जिप्सम फॉल्स सीलिंग", "Joint-free modern finish with cove lighting for halls and bedrooms.", "gypsum-false-ceiling", Home],
  ["PVC False Ceiling", "पीवीसी फॉल्स सीलिंग", "Waterproof panels for kitchens, bathrooms and damp spaces.", "pvc-false-ceiling", Droplets],
  ["Grid Ceiling", "ग्रिड सीलिंग", "Smart demountable tiles for offices, clinics and retail spaces.", "grid-ceiling", Ruler],
  ["Partition Walls", "पार्टिशन वॉल", "Drywall and glass partitions that keep your layout flexible.", "partition-wall", Wrench],
  ["WPC Wall Panels", "डब्ल्यूपीसी वॉल पैनल", "Wood-look fluted finishes for TV walls, receptions and niches.", "wpc-wall-panel", Sparkles],
  ["UV Marble Sheets", "यूवी मार्बल शीट", "High-gloss wall cladding with a premium look and easy upkeep.", "uv-marble-sheet", Star],
  ["Modular TV Units", "मॉड्यूलर टीवी यूनिट", "Custom storage, concealed wiring and a clean focal wall.", "modular-tv-unit", Hammer],
  ["Artificial Grass", "आर्टिफिशियल ग्रास", "Evergreen, zero-maintenance surfaces for balconies and terraces.", "artificial-grass", Droplets],
] as const

const values = [
  ["01", "Clear quotations", "Itemised pricing, explained before work begins."],
  ["02", "Neat workmanship", "Low-dust installation with a clean final handover."],
  ["03", "Local expertise", "On-ground advice for Chandigarh homes and businesses."],
  ["04", "One-year warranty", "Written peace of mind after your project is complete."],
]

const wa = "https://wa.me/917258951213?text=Hi%2C%20I%20need%20a%20free%20site%20visit."

export default function HomePage() {
  const businessSchema = { "@context": "https://schema.org", "@type": "HomeAndConstructionBusiness", name: "False Ceiling Service Chandigarh", url: "https://falseceilingservice.com", telephone: "+91 7258951213", image: "https://falseceilingservice.com/images/hero-interior.png", priceRange: "₹₹", areaServed: [{ "@type": "City", name: "Chandigarh" }, { "@type": "Place", name: "Mani Majra" }], serviceType: ["False ceiling installation", "Interior wall panels", "Partition walls", "Modular TV units"], address: { "@type": "PostalAddress", addressLocality: "Mani Majra", addressRegion: "Chandigarh", postalCode: "160101", addressCountry: "IN" }, sameAs: ["https://falseceilingservice.com"] }
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: ["How much does a false ceiling cost in Chandigarh?", "Which ceiling is best for a damp room?", "Do you provide lighting and electrical work?", "How do I book a site visit?"].map((question) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: "Contact False Ceiling Service Chandigarh for a free site visit and a clear recommendation based on your room, material and requirements." } })) }
  return <main id="top">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(businessSchema) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
    <a className="skip-link" href="#main-content">Skip to content</a>
    <div className="announcement"><span><Clock3 size={14} /> Site visits available this week in Mani Majra</span><a href={wa} target="_blank" rel="noreferrer">Get a free quote <ArrowRight size={14} /></a></div>
    <header className="site-header"><Link className="brand" href="#top" aria-label="False Ceiling Service home"><span className="brand-mark"><Home size={18} /></span><span>False Ceiling<br /><strong>Service</strong></span></Link><nav aria-label="Main navigation"><Link href="#services">Services</Link><Link href="#projects">Projects</Link><Link href="#process">Process</Link><Link href="#faq">FAQ</Link><Link href="#contact">Contact</Link></nav><a className="header-cta" href="tel:+917258951213"><Phone size={16} /> Call Now</a></header>
    <div id="main-content">
      <section className="hero hero-editorial section-shell"><div className="hero-copy"><div className="eyebrow"><MapPin size={15} /> Serving Mani Majra and Chandigarh</div><h1>Beautiful ceilings.<br /><em>Better interiors.</em></h1><p className="hero-lede">Professional false ceiling and interior work, planned around your space, budget and everyday life.<br /><span lang="hi">साफ काम, सही सलाह और भरोसेमंद installation — आपके घर या business के लिए।</span></p><div className="hero-note"><Check size={16} /> Free site visit <span>·</span> Direct contractor pricing <span>·</span> 1-year warranty</div><div className="hero-actions"><a className="button button-primary" href={wa} target="_blank" rel="noreferrer"><MessageCircle size={18} /> Book a free site visit <ArrowRight size={17} /></a><a className="button button-secondary" href="tel:+917258951213"><Phone size={17} /> Talk to an expert</a></div><div className="rating"><span className="stars">★★★★★</span><span><strong>Trusted local workmanship</strong><br />Homes, offices & shops across Chandigarh</span></div><div className="hero-contact-card"><div className="contact-avatar"><Phone size={17} /></div><div><span>Speak with our team</span><strong>+91 72589 51213</strong><small>Mon–Sat · 9:00 AM–7:00 PM</small></div><a href="tel:+917258951213" aria-label="Call False Ceiling Service Chandigarh"><ArrowRight size={18} /></a></div></div><div className="hero-visual hero-photo"><img src="/images/hero-interior.png" alt="Elegant false ceiling with warm cove lighting in a modern interior" /><div className="visual-label">FALSE CEILING / CHANDIGARH</div><div className="visual-stamp">PROJECT<br /><strong>01</strong></div><div className="visual-caption"><span>Design inspiration</span><strong>Made for your space.</strong></div></div></section>
      <section className="trust-strip"><div className="section-shell trust-grid"><div><span className="trust-number">01</span><strong>Free site visit</strong><p>We measure first and recommend what actually fits.</p></div><div><span className="trust-number">02</span><strong>Transparent pricing</strong><p>Clear quotations with no surprise additions.</p></div><div><span className="trust-number">03</span><strong>Clean installation</strong><p>Reliable local team, neat work and timely handover.</p></div></div></section>
      <section className="intro section-shell"><div className="section-kicker">A considered approach</div><div className="intro-grid"><h2>Make every room<br /><em>feel more intentional.</em></h2><p>From the first measurement to the final light fitting, we bring practical design thinking to your interior project.<br /><br /><span lang="hi">छत सिर्फ ऊपर की जगह नहीं है — सही design से पूरा कमरा बेहतर महसूस होता है।</span></p></div></section>
      <section id="services" className="services section-shell"><div className="section-heading"><div><div className="section-kicker">What we transform</div><h2>One team for<br /><em>the whole finish.</em></h2></div><p>Explore our most requested ceiling and interior services for homes, offices, shops and rental properties.</p></div><div className="service-grid">{services.map(([title, hindi, description, slug, Icon]) => <Link className="service-card" href={`/services/${slug}`} key={title}><span className="service-icon"><Icon size={21} /></span><h3>{title}</h3><small lang="hi">{hindi}</small><p>{description}</p><span className="card-link">View service <ChevronRight size={15} /></span></Link>)}</div></section>
      <section id="projects" className="project-showcase section-shell"><div className="showcase-copy"><div className="section-kicker">Design inspiration</div><h2>See what your<br /><em>space could become.</em></h2><p>Premium ceiling details, warm lighting, and clean finishes — thoughtfully planned interiors for your home.</p><Link className="text-link" href="/services">Explore our services <ArrowRight size={16} /></Link></div><div className="showcase-image"><img src="/images/project-showcase.png" alt="Modern living room with a premium false ceiling and ambient lighting" /><span>Concept project / कॉन्सेप्ट प्रोजेक्ट</span></div></section>
      <section className="values"><div className="section-shell"><div className="section-kicker">The difference</div><h2>Good work should come<br /><em>with good assurance.</em></h2><p className="trust-intro">A professional finish is more than a good-looking ceiling. It is clear communication, dependable execution and support after handover.</p><div className="value-grid">{values.map(([number, title, description]) => <div className="value-item" key={number}><span>{number}</span><ShieldCheck size={21} /><strong>{title}</strong><small>{description}</small></div>)}</div></div></section>
      <section id="process" className="process section-shell"><div className="section-heading"><div><div className="section-kicker">Our process</div><h2>Simple from<br /><em>start to finish.</em></h2></div><p>No confusing handoffs. Talk directly with our team and know what happens next.</p></div><div className="process-grid"><div className="process-step"><span>01</span><MessageCircle size={22} /><h3>Tell us your idea</h3><p>Share photos, room size or simply tell us what you want to improve.</p></div><div className="process-step"><span>02</span><MapPin size={22} /><h3>Free site visit</h3><p>We visit, measure accurately and suggest the right material and finish.</p></div><div className="process-step"><span>03</span><Wrench size={22} /><h3>Clean installation</h3><p>Our team completes the work carefully, safely and on the agreed schedule.</p></div><div className="process-step"><span>04</span><ShieldCheck size={22} /><h3>Final handover</h3><p>We check the details, clean the space and stand behind the finished work.</p></div></div></section>
      <section id="faq" className="faq section-shell"><div className="section-heading"><div><div className="section-kicker">Questions, answered</div><h2>Before you<br /><em>get started.</em></h2></div><p>Still unsure what your room needs? Call us for straightforward advice.</p></div><div className="faq-list"><details open><summary>How much does a false ceiling cost in Chandigarh?</summary><p>Pricing depends on material, design, lighting and area. We provide a clear itemised quote after a free site measurement, so you know the actual cost before starting.</p></details><details><summary>Which ceiling is best for a damp room?</summary><p>PVC is usually the most practical choice for bathrooms, kitchens and moisture-prone spaces. We will recommend the right option based on ventilation and usage.</p></details><details><summary>Do you provide lighting and electrical work?</summary><p>Yes. We can plan cove lighting, spotlights, concealed wiring and access points as part of the ceiling installation.</p></details><details><summary>How do I book a site visit?</summary><p>WhatsApp your location and a few photos, or call us directly. We serve Mani Majra and Chandigarh with free initial site visits.</p></details></div></section>
      <section id="contact" className="contact section-shell"><div><div className="eyebrow"><Clock3 size={15} /> Ready when you are</div><h2>Let&apos;s make your<br /><em>space feel new.</em></h2><p>आज ही requirement share करें। बिना sales pressure के सही सलाह पाएं।</p></div><div className="contact-actions"><a className="button button-light" href={wa} target="_blank" rel="noreferrer"><MessageCircle size={18} /> WhatsApp us / संदेश करें</a><a className="contact-phone" href="tel:+917258951213"><Phone size={16} /> +91 7258951213</a></div></section>
    </div>
    <footer className="footer"><div className="section-shell footer-grid"><div><Link className="brand brand-footer" href="#top"><span className="brand-mark"><Home size={18} /></span><span>False Ceiling<br /><strong>Service</strong></span></Link><p>Practical interior finishes, installed with care in Chandigarh.<br />चंडीगढ़ में भरोसेमंद interior solutions.</p></div><div><strong>Visit / service area</strong><p>Mani Majra, Chandigarh<br />PIN: 160101</p></div><div><strong>Get in touch / संपर्क</strong><p><a href="tel:+917258951213">+91 7258951213</a><br /><a href="https://falseceilingservice.com">falseceilingservice.com</a><br /><a href={wa} target="_blank" rel="noreferrer">WhatsApp us / संदेश करें</a></p></div></div><div className="section-shell footer-bottom"><span>© 2026 False Ceiling Service</span><span>Made for Chandigarh homes & businesses</span><span>Design & developed by Jitendra Kumar · <a href="https://wa.me/918651070831" target="_blank" rel="noreferrer">WhatsApp 8651070831</a> · <a href="tel:+918541849118">Call 8541849118</a></span></div></footer>
  </main>
}
