import { ArrowRight, Check, ChevronRight, Clock3, Droplets, Hammer, Home, MapPin, MessageCircle, Phone, Ruler, ShieldCheck, Sparkles, Star, Wrench } from "lucide-react"

const services = [
  ["Gypsum False Ceiling", "जिप्सम फॉल्स सीलिंग", "gypsum-false-ceiling", "₹75–₹210 / sq.ft", "Joint-free modern finish with cove lighting for halls and bedrooms.", Home],
  ["PVC False Ceiling", "पीवीसी फॉल्स सीलिंग", "pvc-false-ceiling", "₹75–₹150 / sq.ft", "100% waterproof ceiling for kitchens, bathrooms and damp spaces.", Droplets],
  ["Grid Ceiling", "ग्रिड सीलिंग", "grid-ceiling", "₹45–₹115 / sq.ft", "Demountable tiles with easy access for office and retail services.", Ruler],
  ["Partition Wall", "पार्टिशन वॉल", "partition-wall", "₹100–₹750 / sq.ft", "Drywall and glass partitions without messy brickwork.", Wrench],
  ["WPC Wall Panel", "डब्ल्यूपीसी वॉल पैनल", "wpc-wall-panel", "₹180–₹650 / sq.ft", "Wood-look fluted louvers for TV walls and receptions.", Sparkles],
  ["UV Marble Sheet", "यूवी मार्बल शीट", "uv-marble-sheet", "₹45–₹120 / sq.ft", "High-gloss, cost-effective cladding for walls and niches.", Star],
  ["Modular TV Unit", "मॉड्यूलर टीवी यूनिट", "modular-tv-unit", "From ₹15,000+", "Custom entertainment units with concealed wiring and storage.", Hammer],
  ["Artificial Grass", "आर्टिफिशियल ग्रास", "artificial-grass", "₹40–₹150 / sq.ft", "Zero-maintenance evergreen flooring for balconies and terraces.", Droplets],
] as const
const values = [["1-Year Written Warranty", "1 साल की लिखित वारंटी"], ["Free On-Site Measurements", "मुफ्त साइट माप"], ["0% Hidden Charges", "कोई छुपा चार्ज नहीं"], ["Expert In-House Installers", "अनुभवी इन-हाउस टीम"]]
const wa = "https://wa.me/917258951213?text=Hi%2C%20I%20need%20a%20free%20site%20visit."

export default function HomePage() { return <main>
  <header className="site-header"><a className="brand" href="#top" aria-label="False Ceiling Service home"><span className="brand-mark"><Home size={18} /></span><span>False Ceiling<br /><strong>Service</strong></span></a><nav aria-label="Main navigation"><a href="#services">Services / सेवाएं</a><a href="#process">Process / प्रक्रिया</a><a href="#contact">Contact / संपर्क</a></nav><a className="header-cta" href="tel:+917258951213"><Phone size={16} /> Call now / कॉल करें</a></header>
  <section id="top" className="hero section-shell"><div className="hero-copy"><div className="eyebrow"><MapPin size={15} /> Mani Majra & Chandigarh / मनी माजरा और चंडीगढ़</div><h1>Beautiful ceilings.<br /><em>Better interiors.</em></h1><p className="hero-lede">Top-rated false ceiling and interior works in Mani Majra, Chandigarh.<br /><span lang="hi">मणि माजरा और चंडीगढ़ में सबसे बेहतरीन फॉल्स सीलिंग और इंटीरियर सर्विस — सही दाम, साफ-सुथरा काम और 1 साल की वारंटी।</span></p><p className="hero-note"><Check size={16} /> Free site visit / मुफ्त साइट विजिट <span>·</span> Direct pricing / सीधी कीमत <span>·</span> 1-year warranty / 1 साल वारंटी</p><div className="hero-actions"><a className="button button-primary" href={wa} target="_blank" rel="noreferrer"><MessageCircle size={18} /> Free Site Visit बुक करें <ArrowRight size={17} /></a><a className="button button-secondary" href="tel:+917258951213"><Phone size={17} /> Talk to an expert</a></div><div className="rating"><span className="stars">★★★★★</span><span><strong>Trusted local workmanship / भरोसेमंद काम</strong><br />Homes, offices & shops across Chandigarh</span></div></div><div className="hero-visual" aria-label="Architectural ceiling detail illustration" role="img"><div className="visual-label">INTERIORS / 2026</div><div className="ceiling-panel panel-one"></div><div className="ceiling-panel panel-two"></div><div className="ceiling-light"></div><div className="visual-caption"><span>Thoughtful details</span><strong>Made for your space.</strong></div></div></section>
  <section className="trust-strip"><div className="section-shell trust-grid"><div><span className="trust-number">01</span><strong>Local & reliable / स्थानीय भरोसा</strong><p>मणि माजरा से Chandigarh की सेवा — भरोसे के साथ।</p></div><div><span className="trust-number">02</span><strong>Clean installation / साफ काम</strong><p>कम धूल वाला काम और साफ-सुथरी finishing.</p></div><div><span className="trust-number">03</span><strong>Clear pricing / पारदर्शी कीमत</strong><p>Itemized quotes with no surprise additions.</p></div></div></section>
  <section className="intro section-shell"><div className="section-kicker">Why choose us / हमें क्यों चुनें</div><div className="intro-grid"><h2>Interiors that feel<br /><em>right from day one.</em></h2><p>Homeowners and businesses choose falseceilingservice.com for reliable, low-dust, timely installations.<br /><br />हम सही सलाह, साफ installation और समय पर काम के साथ आपके घर या business को बेहतर बनाते हैं।</p></div></section>
  <section id="services" className="services section-shell"><div className="section-heading"><div><div className="section-kicker">Our services / हमारी सेवाएं</div><h2>Built around how<br /><em>you live & work.</em></h2></div><p>हमारी मुख्य सेवाएं (Our Core Services) — अपने घर और ऑफिस के लिए चुनें बेहतरीन डिज़ाइन।<br />Practical advice, honest pricing and finishes for every budget.</p></div><div className="service-grid">{services.map(([title, hindi, slug, price, text, Icon]) => <article className="service-card" key={slug}><div className="service-icon"><Icon size={21} /></div><div className="service-card-top"><h3>{title}</h3><small>{hindi}</small><span>{price}</span></div><p>{text}</p><a href={`/services/${slug}`}>Discuss this service / जानकारी लें <ChevronRight size={15} /></a></article>)}</div></section>
  <section className="values"><div className="section-shell"><div className="section-kicker">The difference / हमारी खासियत</div><h2>Good work should come<br /><em>with good assurance.</em></h2><div className="value-grid">{values.map(([en, hi], i) => <div className="value-item" key={en}><span>0{i + 1}</span><ShieldCheck size={21} /><strong>{en}</strong><small>{hi}</small></div>)}</div></div></section>
  <section id="process" className="process section-shell"><div className="section-heading"><div><div className="section-kicker">Our process / काम की प्रक्रिया</div><h2>Simple from<br /><em>start to finish.</em></h2></div><p>No confusing handoffs. सीधे team से बात करें।</p></div><div className="process-grid"><div className="process-step"><span>01</span><MessageCircle size={22} /><h3>Call or WhatsApp <small>(फोन या व्हाट्सएप करें)</small></h3><p>कॉल या WhatsApp पर अपनी जरूरत बताएं।</p><a href="tel:+917258951213">+91 7258951213</a></div><div className="process-step"><span>02</span><MapPin size={22} /><h3>Free Site Visit &amp; Measurement <small>(फ्री साइट विजिट और माप)</small></h3><p>मुफ्त measurement और itemized quotation.</p></div><div className="process-step"><span>03</span><Wrench size={22} /><h3>Clean Panel Installation <small>(कम धूल वाला पैनल इंस्टॉलेशन)</small></h3><p>साफ, सुरक्षित और तय समय पर installation.</p></div><div className="process-step"><span>04</span><ShieldCheck size={22} /><h3>Handover &amp; 1-Year Warranty <small>(काम पूरा और 1 साल की वारंटी)</small></h3><p>काम के बाद 1-year written warranty.</p></div></div></section>
  <section id="contact" className="contact section-shell"><div><div className="eyebrow"><Clock3 size={15} /> Ready when you are / आप तैयार हों तो हम भी</div><h2>Let&apos;s make your<br /><em>space feel new.</em></h2><p>आज ही requirement share करें। बिना sales pressure के सही सलाह पाएं।</p></div><div className="contact-actions"><a className="button button-light" href={wa} target="_blank" rel="noreferrer"><MessageCircle size={18} /> WhatsApp us / संदेश करें</a><a className="contact-phone" href="tel:+917258951213"><Phone size={16} /> +91 7258951213</a></div></section>
  <footer className="footer"><div className="section-shell footer-grid"><div><a className="brand brand-footer" href="#top"><span className="brand-mark"><Home size={18} /></span><span>False Ceiling<br /><strong>Service</strong></span></a><p>Practical interior finishes, installed with care in Chandigarh.<br />चंडीगढ़ में भरोसेमंद interior solutions.</p></div><div><strong>Visit / service area</strong><p>Mani Majra, Chandigarh<br />PIN: 160101</p></div><div><strong>Get in touch / संपर्क</strong><p><a href="tel:+917258951213">+91 7258951213</a><br /><a href="https://falseceilingservice.com">falseceilingservice.com</a></p></div></div><div className="section-shell footer-bottom"><span>© 2026 False Ceiling Service</span><span>Made for Chandigarh homes & businesses</span></div></footer>
</main> }
