import Link from "next/link"
import { ArrowRight, Check, ChevronRight, Clock3, Droplets, Hammer, Home, MapPin, MessageCircle, Phone, Ruler, ShieldCheck, Sparkles, Star, Wrench } from "lucide-react"

const services = [
  ["Gypsum False Ceiling", "जिप्सम फॉल्स सीलिंग", "gypsum-false-ceiling", "₹75–₹210 / sq.ft", "Joint-free modern finish with cove lighting for halls and bedrooms.", Home],
  ["PVC False Ceiling", "पीवीसी फॉल्स सीलिंग", "pvc-false-ceiling", "₹75–₹150 / sq.ft", "100% waterproof ceiling for kitchens, bathrooms and damp spaces.", Droplets],
  ["Grid Ceiling", "ग्रिड सीलिंग", "grid-ceiling", "₹45–₹115 / sq.ft", "Demountable tiles with easy access for office and retail services.", Ruler],
  ["Partition Wall", "पार्टिशन वॉल", "partition-wall", "₹100–₹750 / sq.ft", "Drywall and glass partitions without messy brickwork.", Wrench],
  ["WPC Wall Panel", "डब्ल्यूपीसी वॉल पैनल", "wpc-wall-panel", "₹180–₹650 / sq.ft", "Wood-look fluted louvers for TV walls and receptions.", Sparkles],
  ["UV Marble Sheet", "यूवी मार्बल शीट", "uv-marble-sheet", "₹45–₹120 / sq.ft", "High-gloss, cost-effective cladding for walls and niches.", Star],
  ["Modular TV Unit", "मॉड्यूलर टीवी यूनिट", "modular-tv-unit", "From ₹15,000+", "Custom entertainment units with concealed wiring and storage.", Hammer],
  ["Artificial Grass", "आर्टिफिशियल ग्रास", "artificial-grass", "₹40–₹150 / sq.ft", "Zero-maintenance evergreen flooring for balconies and terraces.", Droplets],
] as const
const values = [["Direct Contractor Pricing", "सीधे ठेकेदार से कीमत"], ["Free On-Site Measurements", "मुफ्त साइट माप"], ["0% Hidden Charges", "कोई छुपा चार्ज नहीं"], ["Expert In-House Installers", "अनुभवी इन-हाउस टीम"]]
const wa = "https://wa.me/917258951213?text=Hi%2C%20I%20need%20a%20free%20site%20visit."

export default function HomePage() {
  const businessSchema = { "@context": "https://schema.org", "@type": "LocalBusiness", name: "False Ceiling Service Chandigarh", url: "https://falseceilingservice.com", telephone: "+91 7258951213", areaServed: ["Chandigarh", "Mani Majra"], serviceType: "False ceiling and interior services" }
  return (<main id="top"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(businessSchema) }} />
  <a className="skip-link" href="#main-content">Skip to content</a>
  <header className="site-header"><Link className="brand" href="#top" aria-label="False Ceiling Service home"><span className="brand-mark"><Home size={18} /></span><span>False Ceiling<br /><strong>Service</strong></span></Link><nav aria-label="Main navigation"><Link href="#top">Home</Link><Link href="/services">Services</Link><Link href="#projects">Projects</Link><Link href="#process">Process</Link><Link href="#contact">Contact</Link></nav><a className="header-cta" href="tel:+917258951213"><Phone size={16} /> Call Now / +91 7258951213</a></header>
  <div id="main-content"><section id="top" className="hero hero-editorial section-shell"><div className="hero-copy"><div className="eyebrow"><MapPin size={15} /> Serving Mani Majra and Chandigarh</div><h1>Beautiful ceilings.<br /><em>Better interiors.</em></h1><p className="hero-lede">Top-rated false ceiling and interior works in Mani Majra, Chandigarh.<br /><span lang="hi">Reliable false ceiling and interior work in Mani Majra and Chandigarh, with clear pricing, neat installation, and a one-year warranty.</span></p><p className="hero-note"><Check size={16} /> Free site visit <span>·</span> Direct pricing <span>·</span> Clear quotation</p><div className="hero-actions"><a className="button button-primary" href={wa} target="_blank" rel="noreferrer"><MessageCircle size={18} /> Book a free site visit <ArrowRight size={17} /></a><a className="button button-secondary" href="tel:+917258951213"><Phone size={17} /> Talk to an expert</a></div><div className="rating"><span className="stars">★★★★★</span><span><strong>Trusted local workmanship</strong><br />Homes, offices & shops across Chandigarh</span></div></div><div className="hero-visual hero-photo"><img src="/images/hero-interior.png" alt="Elegant false ceiling with warm cove lighting in a modern interior" /><div className="visual-label">FALSE CEILING / CHANDIGARH</div><div className="visual-stamp">PROJECT<br /><strong>01</strong></div><div className="visual-caption"><span>Design inspiration</span><strong>Made for your space.</strong></div></div></section>
  <section id="projects" className="project-showcase section-shell"><div className="showcase-copy"><div className="section-kicker">Design inspiration</div><h2>See what your<br /><em>space could become.</em></h2><p>Premium ceiling details, warm lighting, and clean finishes — thoughtfully planned interiors for your home.</p><Link className="text-link" href="#services">Explore services <ArrowRight size={16} /></Link></div><div className="showcase-image"><img src="/images/project-showcase.png" alt="Modern living room with a premium false ceiling and ambient lighting" /><span>Concept project / कॉन्सेप्ट प्रोजेक्ट</span></div></section>
  <section className="trust-strip"><div className="section-shell trust-grid"><div><span className="trust-number">01</span><strong>Local and reliable</strong><p>Serving Mani Majra and Chandigarh with care.</p></div><div><span className="trust-number">02</span><strong>Clean installation</strong><p>Low-dust work with a clean finish.</p></div><div><span className="trust-number">03</span><strong>Clear pricing / पारदर्शी कीमत</strong><p>Itemized quotes with no surprise additions.</p></div></div></section>
  <section className="intro section-shell"><div className="section-kicker">Why choose us</div><div className="intro-grid"><h2>Interiors that feel<br /><em>right from day one.</em></h2><p>Homeowners and businesses choose falseceilingservice.com for reliable, low-dust, timely installations.<br /><br />हम सही सलाह, साफ installation और समय पर काम के साथ आपके घर या business को बेहतर बनाते हैं।</p></div></section>
  <section id="services" className="services-preview section-shell"><div className="section-heading"><div><div className="section-kicker">Our services</div><h2>Find the right<br /><em>finish for your space.</em></h2></div><p>Ceilings, partitions, wall panels and custom interiors — explore every service on one dedicated page.</p></div><div className="services-preview-panel"><span className="service-entry-number">08</span><div><strong>Explore all services</strong><small>Pricing, details and five-photo galleries</small></div><Link className="button button-primary" href="/services">Explore services <ArrowRight size={17} /></Link></div></section>
  <section className="values"><div className="section-shell"><div className="section-kicker">The difference</div><h2>Good work should come<br /><em>with good assurance.</em></h2><p className="trust-intro">Clear baat, साफ quotation और जिम्��ेदारी से किया गया installation — यही हमारा वादा है।</p><div className="value-grid">{values.map(([en, hi], i) => <div className="value-item" key={en}><span>0{i + 1}</span><ShieldCheck size={21} /><strong>{en}</strong><small>{hi}</small></div>)}</div></div></section>
  <section id="process" className="process section-shell"><div className="section-heading"><div><div className="section-kicker">Our process</div><h2>Simple from<br /><em>start to finish.</em></h2></div><p>No confusing handoffs. Talk directly with our team.</p></div><div className="process-grid"><div className="process-step"><span>01</span><MessageCircle size={22} /><h3>Call or WhatsApp <small>(फोन या व्हाट्सएप करें)</small></h3><p>कॉल या WhatsApp पर अपनी जरूरत बताएं।</p><a href="tel:+917258951213">+91 7258951213</a></div><div className="process-step"><span>02</span><MapPin size={22} /><h3>Free Site Visit &amp; Measurement <small>(फ्री साइट विजिट और माप)</small></h3><p>मुफ्त measurement और itemized quotation.</p></div><div className="process-step"><span>03</span><Wrench size={22} /><h3>Clean Panel Installation <small>(कम धूल वाला पैनल इंस्टॉलेशन)</small></h3><p>साफ, सुरक्षित और तय समय पर installation.</p></div><div className="process-step"><span>04</span><ShieldCheck size={22} /><h3>Final Handover <small>(काम पूरा और साफ handover)</small></h3><p>अंत में पूरा काम check करके साफ handover.</p></div></div></section>
  <section id="contact" className="contact section-shell"><div><div className="eyebrow"><Clock3 size={15} /> Ready when you are</div><h2>Let&apos;s make your<br /><em>space feel new.</em></h2><p>आज ही requirement share करें। बिना sales pressure के सही सलाह पाएं।</p></div><div className="contact-actions"><a className="button button-light" href={wa} target="_blank" rel="noreferrer"><MessageCircle size={18} /> WhatsApp us / संदेश करें</a><a className="contact-phone" href="tel:+917258951213"><Phone size={16} /> +91 7258951213</a></div></section></div>
  <footer className="footer"><div className="section-shell footer-grid"><div><Link className="brand brand-footer" href="#top"><span className="brand-mark"><Home size={18} /></span><span>False Ceiling<br /><strong>Service</strong></span></Link><p>Practical interior finishes, installed with care in Chandigarh.<br />चंडीगढ़ में भरोसेमंद interior solutions.</p></div><div><strong>Visit / service area</strong><p>Mani Majra, Chandigarh<br />PIN: 160101</p></div><div><strong>Get in touch / संपर्क</strong><p><a href="tel:+917258951213">+91 7258951213</a><br /><a href="/">falseceilingservice.com</a><br /><a href={wa} target="_blank" rel="noreferrer">WhatsApp us / संदेश करें</a></p></div></div><div className="section-shell footer-bottom"><span>© 2026 False Ceiling Service</span><span>Made for Chandigarh homes & businesses</span><span>Design & developed by Jitendra Kumar · <a href="https://wa.me/918651070831" target="_blank" rel="noreferrer">WhatsApp 8651070831</a> · <a href="tel:+918541849118">Call 8541849118</a></span></div></footer>
</main>)
}
