import { ArrowLeft, Check, MessageCircle, Phone, ShieldCheck } from "lucide-react"
import Link from "next/link"

const services: Record<string, { title: string; price: string; summary: string; details: string[] }> = {
  "gypsum-false-ceiling": { title: "Gypsum False Ceiling", price: "₹75–₹210 / sq.ft", summary: "Modern, joint-free ceiling finishes designed to make halls, bedrooms, and living rooms feel brighter and more finished.", details: ["Cove lighting and layered ceiling designs", "Smooth, paint-ready finish with neat joints", "Ideal for living rooms, bedrooms, offices, and halls"] },
  "pvc-false-ceiling": { title: "PVC False Ceiling", price: "₹75–₹150 / sq.ft", summary: "A practical 100% waterproof ceiling solution for kitchens, bathrooms, balconies, and utility areas.", details: ["Water-resistant panels that are easy to clean", "Quick installation with low maintenance", "Suitable for kitchens, bathrooms, and damp areas"] },
  "grid-ceiling": { title: "Grid Ceiling", price: "₹45–₹115 / sq.ft", summary: "Demountable ceiling tiles that keep offices and retail spaces easy to maintain, repair, and update.", details: ["Easy access to electrical and AC services", "Replaceable tiles for simple maintenance", "A clean professional look for commercial interiors"] },
  "partition-wall": { title: "Partition Wall", price: "₹100–₹750 / sq.ft", summary: "Create useful rooms and work zones with sturdy drywall or glass partitions—without messy brickwork.", details: ["Drywall and glass options for homes and offices", "Faster, cleaner alternative to masonry walls", "Can include insulation, doors, and electrical points"] },
  "wpc-wall-panel": { title: "WPC Wall Panel", price: "₹180–₹650 / sq.ft", summary: "Premium wood-look fluted louvers that add warmth and character to TV walls, receptions, and feature areas.", details: ["Fluted and contemporary wood-look finishes", "Great for TV feature walls and reception backdrops", "Low-maintenance panels with a premium appearance"] },
  "uv-marble-sheet": { title: "UV Marble Sheet", price: "₹45–₹120 / sq.ft", summary: "High-gloss marble-style cladding that delivers a premium look at a practical price.", details: ["Cost-effective alternative to natural marble", "Useful for pooja rooms, bathroom walls, and niches", "Easy-to-clean surface with bold patterns"] },
  "modular-tv-unit": { title: "Modular TV Unit", price: "From ₹15,000+", summary: "A custom-built entertainment unit planned around your TV, storage needs, and room proportions.", details: ["Concealed wiring for a clean finished wall", "Open shelves, drawers, and storage as required", "Designs matched to your ceiling and wall panels"] },
  "artificial-grass": { title: "Artificial Grass", price: "₹40–₹150 / sq.ft", summary: "Bring an evergreen outdoor feel to balconies and terraces without watering, trimming, or daily upkeep.", details: ["Zero-maintenance green flooring", "Suitable for balconies, terraces, and play areas", "Multiple pile heights and finishes available"] },
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const service = services[slug]
  return { title: service ? `${service.title} in Chandigarh | False Ceiling Service` : "Interior Services in Chandigarh | False Ceiling Service", description: service?.summary }
}

export default async function ServicePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const service = services[slug] ?? services["gypsum-false-ceiling"]
  return <main className="service-detail-page"><header className="site-header"><Link className="brand" href="/"><span className="brand-mark">FC</span><span>False Ceiling<br /><strong>Service</strong></span></Link><a className="header-cta" href="tel:+917258951213"><Phone size={16} /> Call now</a></header><section className="detail-hero section-shell"><Link className="back-link" href="/#services"><ArrowLeft size={16} /> Back to all services</Link><div className="detail-kicker">Service in Mani Majra & Chandigarh</div><h1>{service.title}</h1><p className="detail-summary">{service.summary}</p><div className="detail-price">Starting estimate: <strong>{service.price}</strong></div><div className="hero-actions"><a className="button button-primary" href="https://wa.me/917258951213?text=Hi%2C%20I%20want%20to%20discuss%20this%20service." target="_blank" rel="noreferrer"><MessageCircle size={18} /> Discuss this service</a><a className="button button-secondary" href="tel:+917258951213"><Phone size={17} /> Call +91 7258951213</a></div></section><section className="detail-content section-shell"><div><div className="section-kicker">Basic details</div><h2>Planned for your<br /><em>space and budget.</em></h2><p>हर काम आपकी जगह, पसंद और बजट के अनुसार plan किया जाता है। Free site visit में हम measurement लेकर material, design और installation की clear जानकारी देते हैं। Final quotation itemized होगा, इसलिए कोई hidden charge नहीं होगा।</p></div><div className="detail-list">{service.details.map((detail) => <div key={detail}><Check size={19} /><span>{detail}</span></div>)}<div><ShieldCheck size={19} /><span>1-year written warranty and expert in-house installation</span></div></div></section><section className="hindi-section section-shell" lang="hi"><div className="section-kicker">हिंदी में जानकारी</div><div className="hindi-grid"><h2>काम शुरू करने से पहले<br /><em>पूरी जानकारी पाएं।</em></h2><div><p>इस service के लिए free site visit और itemized quotation उपलब्ध है। हमें WhatsApp पर अपनी requirement, room की photo या approximate size भेजें—हम आपको सही option और estimated cost समझाएंगे।</p><a className="button button-primary" href="https://wa.me/917258951213?text=Namaste%2C%20mujhe%20is%20service%20ke%20baare%20mein%20jaankari%20chahiye." target="_blank" rel="noreferrer">WhatsApp पर पूछें <MessageCircle size={17} /></a></div></div></section><footer className="footer"><div className="section-shell footer-bottom"><span>Mani Majra, Chandigarh · 160101</span><a href="tel:+917258951213">+91 7258951213</a></div></footer></main>
}

export function generateStaticParams() { return Object.keys(services).map((slug) => ({ slug })) }
